### ISSUE TITLE
Request new Ruby release

### ISSUE THREAD

**Issue by ghost** [cygwinports/ruby#1]
Please release new Cygwin Ruby. Current version is 2.3.6 (Dec 2017), and since
then 2 versions have dropped [1]:

- 2.4.3 (Dec 2017)
- 2.5.0 (Dec 2017)

2.4.0 introduced Enumerable#sum [2], and changes to class [3]

[1] http://github.com/ruby/ruby/tags
[2] http://stackoverflow.com/a/41235616
[3] http://stackoverflow.com/a/21411269

**Comment by yselkowitz** [comment]
At this point I plan to jump to 2.5.1 sometime after it is out.

**Comment by svnpenn** [comment]
Its out

http://github.com/ruby/ruby/releases/tag/v2_5_1

**Comment by svnpenn** [comment]
?

**Comment by svnpenn** [comment]
https://github.com/cygwinports/ruby/pull/2

**Comment by cup** [comment]
https://github.com/cygwinports/ruby/issues/1
https://github.com/cygwinports/ruby/pull/3
https://github.com/fd00/yacp/issues/21

**Comment by cup** [comment]
https://github.com/cygwinports/ruby/issues/1
https://github.com/cygwinports/ruby/pull/2
https://github.com/cygwinports/ruby/pull/3
https://github.com/fd00/yacp/issues/21
